import Config

# The address the endpoint listens on, as a tuple, from BIND_IP. Parsed here
# rather than in the application because config files are evaluated before the
# application is compiled, so nothing of ours exists yet.
{:ok, bind_ip} =
  System.get_env("BIND_IP", "127.0.0.1") |> String.to_charlist() |> :inet.parse_address()

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :station, StationWeb.Endpoint,
  # Loopback by default, because a development machine has no business being
  # reachable from the coffee shop it is sitting in.
  #
  # The booth is the exception and the reason both of these are environment
  # variables: the station runs on a laptop on its own hotspot, so it has to
  # listen on the address the phones can see.
  #
  #     BIND_IP=0.0.0.0 mix phx.server
  #
  # PORT is honoured too, so a second station can be started next to a running
  # one without stopping it.
  http: [
    ip: bind_ip,
    port: String.to_integer(System.get_env("PORT", "4000"))
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "dc2NU0DwWCcSqmmsNVfB6c+K0AlUl8xL0fiTx8cdJktbw6z+zbqdcv15e65vvh6b",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:station, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:station, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :station, StationWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/station_web/router\.ex$"E,
      ~r"lib/station_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :station, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Station: local defaults. The prod values come from the environment, see
# config/runtime.exs.
config :station,
  leaderboard_path: "priv/leaderboard.ets",
  ops_token: "dev",
  ops_username: "ops",
  ops_password: "ops"
